# -*- coding: utf-8 -*-
"""finance_tracker.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ezTE9wHXyS_mBfzJtzfsN_bzznuXwVY8
"""

def welcome():
  print("Welcome to your personal finance tracker!")


def menu():
  expenses={}
  while True:
    print("Welcome the the menu")
    print("1. Add expense")
    print("2. View all expenses")
    print("3. View summary by category")
    print("4. Exit")
    decision=input("Choose an option 1-4: ").strip()
    if decision=="1":
      add_expense(expenses)
    elif decision=="2":
      view_expenses(expenses)
    elif decision=="3":
      view_summary(expenses)
    elif decision=="4":
      print("thank you for using the finance tracker.")
      break
    else:
      print("please enter an option 1-4")


def add_expense(data):
  description=input("Please enter description of expense, or done to close:  ")
  if description.strip().lower()=="cancel":
    print("canceled.")
    return
  if not description.strip():
    print("description cannot be empty. Try again")
    return
  category=input("Enter category of expense:  ")
  if not category.strip():
    print("category cannot be empty. Try again")
    return
  try:
    amount=float(input("Enter expense amount:  "))
    if amount <=0:
      print("amount cannot be 0")
      return
  except ValueError:
    print("please enter a valid number for amount")
    return
  expense=(description,amount)
  if category in data:
    data[category].append(expense)
  else:
    data[category]=[expense]
  print("expense added.")


def view_expenses(data):
  if not data:
    print("no expenses")
    return
  for category, expense_list in data.items():
    print(f" Category: {category}")
    for description, amount in expense_list:
      print(f" {description}: ${amount}")

def view_summary(data):
  if not data:
    print("no expenses")
    return
  print("Summary:")
  for category, expense_list in data.items():
    total=0
    for description, amount in expense_list:
      total += amount
    print(f"{category}: ${total}")

welcome()
menu()

